server:
  port: 8085

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  application:
    name: account-service

  data:
    mongodb:
      host: localhost
      port: 27019
      database: journal_db
